### ISSUE TITLE
Provide editable figures

### ISSUE THREAD

**Issue by palemieux** [SMPTE/st429-5#1]

**Comment by jhursty** [comment]
I have these in OmniGraffle format. Github won't accept them as uploads to this issue. I can submit them as a pull request, but I don't know if the format suits the requirements. Maybe they have to be converted to something more portable? I'm happy to share them. Please advise.

**Comment by palemieux** [comment]
You can either ZIP or export as SVG or maybe both :)

**Comment by jhursty** [comment]
using zip to get around the format thing
[st-429-5-figures.zip](https://github.com/SMPTE/st429-5/files/11237475/st-429-5-figures.zip)

**Comment by palemieux** [comment]
Closed by https://github.com/SMPTE/st429-5-private/commit/c70088202c7ede07dc71d0beefd3213237eb4777

**Comment by jhursty** [comment]
posting figures as SVG
[st-429-5-figures-svg.zip](https://github.com/SMPTE/st429-5/files/12233169/st-429-5-figures-svg.zip)
