### ISSUE TITLE
Missing abbreviation 

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/st429-5#3]
Second paragraph in 8:
```
When encrypting Ancillary Resources, the Generic Stream Data Element KLV packet in the Generic Stream Partition that contains the resource data shall be contained in an Encrypted Triplet per [SMPTE ST 429-6](https://doc.smpte-doc.org/st429-5-private/2f784375882463b97a06eef2e28f8ebfe075813b/#bib-st-429-6). If the optional MIC value is present in the EKLV packet, the Sequence Number value shall increment with each successive encrypted Ancillary Resource (i.e., the first Ancillary Resource EKLV packet shall have a Sequence Number that is one greater than that of the Timed Text Resource EKLV packet, the second Ancillary Resource EKLV packet shall have a Sequence Number that is two greater than that of the Timed Text Resource EKLV packet, etc.)
```

`EKLV` should be defined on first usage as `Generic Stream Data Element KLV (EKLV)`, or conversely added to the Terms and Definitions section as a defined abbreviation.

**Comment by palemieux** [comment]
EKLV should be Encrypted Triplet, right?

**Comment by jhursty** [comment]
"EKLV" should be defined as "Encrypted KLV", or it should be replaced wherever used with "Encrypted Triplet". The single Generic Stream Data Element KLV packet may or may not be encrypted, so "Generic Stream Data Element KLV (EKLV)" would be incorrect.

**Comment by palemieux** [comment]
AFAIK EKLV is only used in one paragraph of this one document, so I proposed removing it: https://github.com/SMPTE/st429-5-private/pull/1
