### ISSUE TITLE
A.4, Table A.6, Row 3, Col 6: Missing Hyperlink? Add to Normative References or the Bibliography

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st429-5#32]
Should there be a hyperlink to ISO/IEC 11578? This is the only mention of this document, so there is nowhere for it to link in the document.
Additionally, should it be added to either the Normative References or the Bibliography?
![image](https://github.com/SMPTE/st429-5/assets/118845840/c5443276-1d30-41ea-b9ab-b26c920c5a7e)

**Comment by palemieux** [comment]
The text between brackets, and thus the reference, duplicates the content of the SMPTE registers and should be removed.
